for_window [app_id="flameshot"] border pixel 0, floating enable, fullscreen disable, move position center 50%

for_window [app_id="com.mitchellh.ghostty" title="nmtui"] floating enable, resize set 1000 800

assign [app_id="firefox"] workspace number 1
assign [app_id="rustdesk"] workspace number 2
assign [app_id="discord"] workspace number 3
assign [app_id="subl"] workspace number 3
assign [app_id="brave"] workspace number 5
assign [app_id="librewolf"] workspace number 6
assign [class="Tor Browser"] workspace number 7

