exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
exec_always systemctl --user start xdg-desktop-portal-wlr

#exec_always autotiling

exec_always lxpolkit
exec_always env XDG_SESSION_DESKTOP=sway conky -c ~/.config/sway/conky/conky.conf

# exec_always wl-paste --watch cliphist -max-items 10 store

