exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP QT_QPA_PLATFORM=wayland
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP QT_QPA_PLATFORM=wayland

exec_always systemctl --user stop xdg-desktop-portal xdg-desktop-portal-wlr xdg-desktop-portal-gtk
exec_always systemctl --user start xdg-desktop-portal-wlr xdg-desktop-portal-gtk
exec_always systemctl --user start xdg-desktop-portal

exec "waybar -c ~/.config/sway/waybar/config.jsonc -s ~/.config/sway/waybar/style4.css"

#exec_always autotiling
#exec "sleep 2 && nm-applet --indicator"

exec "sleep 2 && udiskie -t --no-menu-checkbox-workaround"
#exec "sleep 2 && blueman-applet"
exec swaybg -i /usr/share/endeavouros/backgrounds/endeavouros-wallpaper.png -m fill
exec firewall-applet
exec lxpolkit
exec env XDG_SESSION_DESKTOP=sway conky -c ~/.config/sway/conky/conky.conf
exec flameshot
exec gammastep-indicator -c ~/.config/gammastep/config_wayland.ini
exec sudo balance.sh
# exec_always wl-paste --watch cliphist -max-items 10 store

exec swayidle -w \
    timeout 500 'swaylock -f' \
    timeout 600 'swaymsg "output * dpms off"' \
        resume 'swaymsg "output * dpms on"' \
    timeout 900 'systemctl suspend' \
    before-sleep 'swaylock -f'
