exec dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
exec_always systemctl --user start xdg-desktop-portal-wlr

exec "waybar -c ~/.config/sway/waybar/config.jsonc -s ~/.config/sway/waybar/style.css"

#exec_always autotiling
exec "sleep 2 && nm-applet --indicator"
#exec "sleep 2 && udiskie -t --no-menu-checkbox-workaround"
#exec "sleep 2 && blueman-applet"
exec swaybg -i ~/Pictures/wallpapers3/landscape0.png -m fit
exec firewall-applet
exec lxpolkit
exec env XDG_SESSION_DESKTOP=sway conky -c ~/.config/sway/conky/conky.conf
exec flameshot
#exec gammastep-indicator
exec ibus-daemon -rxRd
#exec sudo balance.sh
# exec_always wl-paste --watch cliphist -max-items 10 store


