# left from eDP-1
#output HDMI-1 {
#	mode 1920x1080@60Hz pos 0 0
#	render_bit_depth 8
#	max_render_time off
#	adaptive_sync off
#}
# Primary right from HDMI-1
#output eDP-1 {
#	mode 1440x900@59.89Hz pos 1920 0
#	render_bit_depth 8
#	max_render_time off
#	adaptive_sync off
#}
output Virtual-1 {
	mode 1440x900@59.89Hz pos 0 0
	render_bit_depth 8
	max_render_time off
	adaptive_sync off
}
# Setting eDP-1 as the dafault focus on startup
#workspace 1 output eDP-1

#exec_always xrandr --output eDP-1 --primary

#init workspaces for every screen
exec "swaysome init 1"
