# left: HDMI-1 (external monitor) - physically on left
output HDMI-A-1 {
    mode 1920x1080@60Hz
    position 0 0
    render_bit_depth 8
    max_render_time off
    adaptive_sync off
}

# right: eDP-1 (laptop screen) - physically on right
output eDP-1 {
    mode 1440x900@59.89Hz
    modeline 106.50  1440 1520 1672 1904  900 903 909 934 -hsync +vsync
    position 1920 0
    render_bit_depth 8
    max_render_time off
    adaptive_sync off
}
#set laptop primary display
#swaymsg output eDP-1 position 0 0
#swaymsg output HDMI-A-1 position 1440 0

#restore back
#swaymsg output HDMI-A-1 position 0 0
#swaymsg output eDP-1 position 1920 0
