#mouse settings values range from -1 (slowest) to 1 (fastest).
input type:pointer {
	accel_profile flat
	pointer_accel -0.5
}


#input type:keyboard {
#	xkb_layout us,ru
#	xkb_variant ,nodeadkeys
#	repeat_delay 650
#	repeat_rate 20
#}

#input type:touchpad {
#	tap enabled
#	matural_scroll enabled
#}

#hide mouse cursor when inactive
#seat seat0 hide_cursor 10000
