bindsym --no-repeat {
  # Move to Workspaces
  $mod+shift+1 move container to workspace number 1
  $mod+shift+2 move container to workspace number 2
  $mod+shift+3 move container to workspace number 3
  $mod+shift+4 move container to workspace number 4
  $mod+shift+5 move container to workspace number 5
  $mod+shift+6 move container to workspace number 6
  $mod+shift+7 move container to workspace number 7
  $mod+shift+8 move container to workspace number 8
  $mod+shift+9 move container to workspace number 9
 
  # Move to next workspace
  $mod+alt+Right workspace next

  # Move to previous workspace
  $mod+alt+Left workspace prev

  # Move container to next monitor
  
 
  # Restart sway
  $mod+shift+r restart

  # Reload sway config
  $mod+shift+c reload
  
  $mod+Return exec alacritty
}
# switch Workspaces
bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9

